.TH MAIL "1" "" "FSF" "User Commands"
.SH NAME
mail \- manual page for mail (GNU Mailutils)
.SH SYNOPSIS
.B mail
[\fIOPTION\fR...] [\fIaddress\fR...]
.SH DESCRIPTION
GNU mail \fB\-\-\fR the standard /bin/mail interface
.SH "REPORTING BUGS"
Report bugs to <bug-mailutils@gnu.org>.
.SH "SEE ALSO"
The full documentation for
.B mail
is maintained as a Texinfo manual.  If the
.B info
and
.B mail
programs are properly installed at your site, the command
.IP
.B info mail
.PP
should give you access to the complete manual.
